name: CI

on:
  push:
  pull_request:
#  schedule:
#    - cron: '9 * * * *'
  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  CACHE_NUMBER: 1 # increase this by one to force new cache

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Test json files pytest
      run: |
        pytest -svx test_json.py

    - name: Test urls pytest
      run: |
        pytest -svx test_urls.py

  generate:
    runs-on: ubuntu-latest
    name: Generate HTML
    needs: test

    steps:
    - uses: actions/checkout@v3

    - name: Cache fetched data
      uses: actions/cache@v3
      with:
        path: cache
        key: osdc-${{ env.CACHE_NUMBER }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Generate HTML pages
      run: |
          python generate.py

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1

  # Deployment job
  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

